In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn import datasets
from sklearn.datasets import make_moons,make_circles

from sklearn.pipeline import Pipeline

from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import PolynomialFeatures

from sklearn.svm import LinearSVC,LinearSVR
from sklearn.svm import SVC,SVR

In [42]:
import warnings
warnings.filterwarnings('ignore')

In [43]:
df = pd.read_csv('ParisHousing.csv')

In [44]:
df.head()

squareMeters  numberOfRooms  hasYard  hasPool  floors  cityCode   
0         75523              3        0        1      63      9373  \
1         80771             39        1        1      98     39381   
2         55712             58        0        1      19     34457   
3         32316             47        0        0       6     27939   
4         70429             19        1        1      90     38045   

   cityPartRange  numPrevOwners  made  isNewBuilt  hasStormProtector   
0              3              8  2005           0                  1  \
1              8              6  2015           1                  0   
2              6              8  2021           0                  0   
3             10              4  2012           0                  1   
4              3              7  1990           1                  0   

   basement  attic  garage  hasStorageRoom  hasGuestRoom      price  
0      4313   9005     956               0             7  7559081.5  
1      3653   2436     128               1             2  8085989.5  
2      2937   8852     135               1             9  5574642.1  
3       659   7141     359               0             3  3232561.2  
4      8435   2429     292               1             4  7055052.0

In [45]:
df.describe()

squareMeters  numberOfRooms       hasYard       hasPool        floors   
count   10000.00000   10000.000000  10000.000000  10000.000000  10000.000000  \
mean    49870.13120      50.358400      0.508700      0.496800     50.276300   
std     28774.37535      28.816696      0.499949      0.500015     28.889171   
min        89.00000       1.000000      0.000000      0.000000      1.000000   
25%     25098.50000      25.000000      0.000000      0.000000     25.000000   
50%     50105.50000      50.000000      1.000000      0.000000     50.000000   
75%     74609.75000      75.000000      1.000000      1.000000     76.000000   
max     99999.00000     100.000000      1.000000      1.000000    100.000000   

           cityCode  cityPartRange  numPrevOwners         made    isNewBuilt   
count  10000.000000   10000.000000   10000.000000  10000.00000  10000.000000  \
mean   50225.486100       5.510100       5.521700   2005.48850      0.499100   
std    29006.675799       2.872024       2.856667      9.30809      0.500024   
min        3.000000       1.000000       1.000000   1990.00000      0.000000   
25%    24693.750000       3.000000       3.000000   1997.00000      0.000000   
50%    50693.000000       5.000000       5.000000   2005.50000      0.000000   
75%    75683.250000       8.000000       8.000000   2014.00000      1.000000   
max    99953.000000      10.000000      10.000000   2021.00000      1.000000   

       hasStormProtector      basement        attic       garage   
count       10000.000000  10000.000000  10000.00000  10000.00000  \
mean            0.499900   5033.103900   5028.01060    553.12120   
std             0.500025   2876.729545   2894.33221    262.05017   
min             0.000000      0.000000      1.00000    100.00000   
25%             0.000000   2559.750000   2512.00000    327.75000   
50%             0.000000   5092.500000   5045.00000    554.00000   
75%             1.000000   7511.250000   7540.50000    777.25000   
max             1.000000  10000.000000  10000.00000   1000.00000   

       hasStorageRoom  hasGuestRoom         price  
count    10000.000000   10000.00000  1.000000e+04  
mean         0.503000       4.99460  4.993448e+06  
std          0.500016       3.17641  2.877424e+06  
min          0.000000       0.00000  1.031350e+04  
25%          0.000000       2.00000  2.516402e+06  
50%          1.000000       5.00000  5.016180e+06  
75%          1.000000       8.00000  7.469092e+06  
max          1.000000      10.00000  1.000677e+07

In [5]:
df.shape

(10000, 17)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 17 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   squareMeters       10000 non-null  int64  
 1   numberOfRooms      10000 non-null  int64  
 2   hasYard            10000 non-null  int64  
 3   hasPool            10000 non-null  int64  
 4   floors             10000 non-null  int64  
 5   cityCode           10000 non-null  int64  
 6   cityPartRange      10000 non-null  int64  
 7   numPrevOwners      10000 non-null  int64  
 8   made               10000 non-null  int64  
 9   isNewBuilt         10000 non-null  int64  
 10  hasStormProtector  10000 non-null  int64  
 11  basement           10000 non-null  int64  
 12  attic              10000 non-null  int64  
 13  garage             10000 non-null  int64  
 14  hasStorageRoom     10000 non-null  int64  
 15  hasGuestRoom       10000 non-null  int64  
 16  price              1000

In [7]:
df['squareMeters'].nunique()

9483

In [8]:
df['hasYard'].value_counts()

hasYard
1    5087
0    4913
Name: count, dtype: int64

# The data is already cleaned hence we can apply various regression algorithms

In [9]:
X = df.drop(columns=['price'])
Y = df['price']

In [10]:
X

squareMeters  numberOfRooms  hasYard  hasPool  floors  cityCode   
0            75523              3        0        1      63      9373  \
1            80771             39        1        1      98     39381   
2            55712             58        0        1      19     34457   
3            32316             47        0        0       6     27939   
4            70429             19        1        1      90     38045   
...            ...            ...      ...      ...     ...       ...   
9995          1726             89        0        1       5     73133   
9996         44403             29        1        1      12     34606   
9997         83841              3        0        0      69     80933   
9998         59036             70        0        0      96     55856   
9999          1440             84        0        0      49     18412   

      cityPartRange  numPrevOwners  made  isNewBuilt  hasStormProtector   
0                 3              8  2005           0                  1  \
1                 8              6  2015           1                  0   
2                 6              8  2021           0                  0   
3                10              4  2012           0                  1   
4                 3              7  1990           1                  0   
...             ...            ...   ...         ...                ...   
9995              7              6  2009           0                  1   
9996              9              4  1990           0                  1   
9997             10             10  2005           1                  1   
9998              1              3  2010           0                  1   
9999              6             10  1994           1                  0   

      basement  attic  garage  hasStorageRoom  hasGuestRoom  
0         4313   9005     956               0             7  
1         3653   2436     128               1             2  
2         2937   8852     135               1             9  
3          659   7141     359               0             3  
4         8435   2429     292               1             4  
...        ...    ...     ...             ...           ...  
9995      9311   1698     218               0             4  
9996      9061   1742     230               0             0  
9997      8304   7730     345               1             9  
9998      2590   6174     339               1             4  
9999      8485   2024     278               1             6  

[10000 rows x 16 columns]

In [39]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 16 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   squareMeters       10000 non-null  int64
 1   numberOfRooms      10000 non-null  int64
 2   hasYard            10000 non-null  int64
 3   hasPool            10000 non-null  int64
 4   floors             10000 non-null  int64
 5   cityCode           10000 non-null  int64
 6   cityPartRange      10000 non-null  int64
 7   numPrevOwners      10000 non-null  int64
 8   made               10000 non-null  int64
 9   isNewBuilt         10000 non-null  int64
 10  hasStormProtector  10000 non-null  int64
 11  basement           10000 non-null  int64
 12  attic              10000 non-null  int64
 13  garage             10000 non-null  int64
 14  hasStorageRoom     10000 non-null  int64
 15  hasGuestRoom       10000 non-null  int64
dtypes: int64(16)
memory usage: 1.2 MB


In [11]:
Y

0       7559081.5
1       8085989.5
2       5574642.1
3       3232561.2
4       7055052.0
          ...    
9995     176425.9
9996    4448474.0
9997    8390030.5
9998    5905107.0
9999     146708.4
Name: price, Length: 10000, dtype: float64

In [12]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size = 0.2, random_state = 1)

# Implementing SVM Regressor with a Poly Kernel 

In [13]:
# Non - Linear SVM Regression

NonLin_reg1 = Pipeline([
  ("scaler", StandardScaler()),
  ("svr", SVR(C = 5, kernel="poly", degree=3, coef0=1)),
])

NonLin_reg1.fit(X_train, y_train)


Pipeline(steps=[('scaler', StandardScaler()),
                ('svr', SVR(C=5, coef0=1, kernel='poly'))])

In [14]:
NonLin_reg1.score(X_test, y_test)

0.004695039469771123

In [15]:
# Non - Linear SVM Regression

NonLin_reg2 = Pipeline([
  ("scaler", StandardScaler()),
  ("svr", SVR(C = 10, kernel="poly", degree=3, coef0=1)),
])

NonLin_reg2.fit(X_train, y_train)

Pipeline(steps=[('scaler', StandardScaler()),
                ('svr', SVR(C=10, coef0=1, kernel='poly'))])

In [16]:
NonLin_reg2.score(X_test, y_test)

0.009457304837888647

In [17]:
# Non - Linear SVM Regression

NonLin_reg3 = Pipeline([
  ("scaler", StandardScaler()),
  ("svr", SVR(C = 5, kernel="poly", degree=5, coef0=1)),
])

NonLin_reg3.fit(X_train, y_train)

Pipeline(steps=[('scaler', StandardScaler()),
                ('svr', SVR(C=5, coef0=1, degree=5, kernel='poly'))])

In [18]:
NonLin_reg3.score(X_test, y_test)

0.010295055253810137

In [19]:
# Non - Linear SVM Regression

NonLin_reg4 = Pipeline([
  ("scaler", StandardScaler()),
  ("svr", SVR(C = 10, kernel="poly", degree=5, coef0=1)),
])

NonLin_reg4.fit(X_train, y_train)

Pipeline(steps=[('scaler', StandardScaler()),
                ('svr', SVR(C=10, coef0=1, degree=5, kernel='poly'))])

In [20]:
NonLin_reg4.score(X_test, y_test)

0.020614329210123072

In [21]:
# Non - Linear SVM Regression

NonLin_reg5 = Pipeline([
  ("scaler", StandardScaler()),
  ("svr", SVR(C = 10, kernel="poly", degree=5, coef0=5)),
])

NonLin_reg5.fit(X_train, y_train)

Pipeline(steps=[('scaler', StandardScaler()),
                ('svr', SVR(C=10, coef0=5, degree=5, kernel='poly'))])

In [22]:
NonLin_reg5.score(X_test, y_test)

0.9999987458992651

# Implementing SVM Regressor with rbf Kernel

In [25]:
# Non - Linear SVM Regression

NonLin_reg1 = Pipeline([
  ("scaler", StandardScaler()),
  ("svr", SVR(C = 10000, kernel = "rbf", gamma=0.1)),
])

NonLin_reg1.fit(X_train, y_train)

Pipeline(steps=[('scaler', StandardScaler()), ('svr', SVR(C=10000, gamma=0.1))])

In [26]:
NonLin_reg1.score(X_test, y_test)

0.4290540388260524

In [27]:
# Non - Linear SVM Regression

NonLin_reg2 = Pipeline([
  ("scaler", StandardScaler()),
  ("svr", SVR(C = 10000, kernel = "rbf", gamma=0.05)),
])

NonLin_reg2.fit(X_train, y_train)

Pipeline(steps=[('scaler', StandardScaler()),
                ('svr', SVR(C=10000, gamma=0.05))])

In [28]:
NonLin_reg2.score(X_test, y_test)

0.742938212727885

In [29]:
# Non - Linear SVM Regression

NonLin_reg3 = Pipeline([
  ("scaler", StandardScaler()),
  ("svr", SVR(C = 5000, kernel = "rbf", gamma=0.1)),
])

NonLin_reg3.fit(X_train, y_train)

Pipeline(steps=[('scaler', StandardScaler()), ('svr', SVR(C=5000, gamma=0.1))])

In [30]:
NonLin_reg3.score(X_test, y_test)

0.23066733307522846

In [31]:
# Non - Linear SVM Regression

NonLin_reg4 = Pipeline([
  ("scaler", StandardScaler()),
  ("svr", SVR(C = 12000, kernel = "rbf", gamma=0.04)),
])

NonLin_reg4.fit(X_train, y_train)

Pipeline(steps=[('scaler', StandardScaler()),
                ('svr', SVR(C=12000, gamma=0.04))])

In [32]:
NonLin_reg4.score(X_test, y_test)

0.8682949434611766

In [37]:
# the model which gives the highest accuracy score is selected for prediction purposes

In [36]:
NonLin_reg5.score(X_test, y_test)

0.9999987458992651

In [38]:
# testing the model

In [40]:
XINPUT = np.array([[19127, 4, 0, 1, 5, 40475, 5, 4, 2004, 1, 1, 2009, 7141, 359, 1, 5]])
XINPUT

array([[19127,     4,     0,     1,     5, 40475,     5,     4,  2004,
            1,     1,  2009,  7141,   359,     1,     5]])

In [46]:
NonLin_reg5.predict(XINPUT)

array([1920271.99119642])

# Loading appropriate model and class objects into pickle file

In [47]:
import pickle

In [48]:
data = {"model":NonLin_reg5}
with open('saved_steps_of_paris_prediction.pkl','wb') as file:
    pickle.dump(data,file)

In [51]:
with open('saved_steps_of_paris_prediction.pkl','rb') as file:
    data = pickle.load(file)

In [52]:
non_linear_regressor = data["model"]

In [53]:
non_linear_regressor.predict(XINPUT)

array([1920271.99119642])